#pragma once

#include "VulkanWrapper/DeviceQueueCreateInfo.h"
#include "VulkanWrapper/SwapChainSupportDetails.h"
#include "VulkanWrapper/PipelineStateCreateInfos.h"
#include "VulkanWrapper/RenderPassCreateInfo.h"
#include "VulkanWrapper/FrameBufferCreateInfo.h"
#include "VulkanWrapper/CreateInfos.inl"
#include "VulkanWrapper/CommandPoolCreateInfo.h"
#include "VulkanWrapper/CommandBufferAllocateInfo.h"
#include "VulkanWrapper/RenderPassBeginInfo.h"
#include "VulkanWrapper/CommandBufferBeginInfo.h"
#include "VulkanWrapper/SemaphoreCreateInfo.h"
#include "VulkanWrapper/FenceCreateInfo.h"
#include "VulkanWrapper/SubmitInfo.h"
#include "VulkanWrapper/PresentInfo.h"
